botToken: bot token
botName: bot username without @
chatId: -1009248292344 # chat id of telegram group to connect
admins: # list of telegram admins user id (to access admin commands in bot)
 - 123453242
 - 678914242
 - 428483242

