name: Telecrafter
main: com.senderman.telecrafter.minecraft.TelecrafterPlugin
version: @version@
api-version: 1.16

permissions:
  telecrafter.receive:
    default: true
    description: Allows you to receive messages from Telegram